name: faiss-pq
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - tqdm>=4.62.0
  - requests>=2.26.0
  - h5py>=3.6.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pyyaml>=6.0
  - pip
  - pip:
    - faiss-cpu>=1.7.0 